# =====================================================================
# HydroponicLettuceEnv.yml
# Description: Advanced configuration for hydroponic lettuce cultivation
# تم تطوير هذا الملف خصيصاً لأنظمة الهيدروبونيك مع إدارة متقدمة للمغذيات
# =====================================================================


GreenLightEnv:

  weather_data_dir: gl_gym/environments/weather
  location: Egypt
  num_params: 208                # عدد معاملات النموذج (محدث)
  nx: 30                          # state vector
  nu: 23                          # عدد عناصر التحكم
  nd: 10                          # عدد الاضطرابات المناخية
  dt: 900           # 15 Min       # [s] خطوة زمنية
  u_min: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  u_max: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
  delta_u_max: 0.1               # معدل التغيير الأقصى
  pred_horizon: 0.5              # [أيام] أفق التنبؤ
  season_length: 60               # طول الموسم (بالأيام)
  start_train_year: 2024         # بداية فترة التدريب
  end_train_year: 2024           # نهاية فترة التدريب
  start_train_day: 59            # بداية فترة التدريب (يوم في السنة)
  end_train_day: 59              # نهاية فترة التدريب (يوم في السنة)
  training: True                  # وضع التدريب

HydroponicLettuceEnv:
  base: GreenLightEnv             # يرث من البيئة الأساسية
  reward_function: 
    - GreenhouseReward
    - reward_params

  observation_modules: 
    - IndoorClimateObservations      # ملاحظات المناخ الداخلي
    - BasicCropObservations          # ملاحظات المحصول الأساسية
    - ControlObservations            # ملاحظات التحكم
    - WeatherObservations            # ملاحظات الطقس
    - TimeObservations               # ملاحظات الوقت
    - WeatherForecastObservations    # ملاحظات توقعات الطقس
    ################################################
    ################################################
    #               تتراجع الهيدروبونيك            #
    ################################################
    ################################################



  constraints:
    # ✅ قيود المناخ الداخلي
    co2_min: 300.0              # الحد الأدنى لثاني أكسيد الكربون [ppm]
    co2_max: 1300.0             # الحد الأقصى لثاني أكسيد الكربون [ppm]
    temp_min: 15.0              # الحد الأدنى لدرجة الحرارة [°C]
    temp_max: 28.0              # الحد الأقصى لدرجة الحرارة [°C]
    rh_min: 50.0                # الحد الأدنى للرطوبة النسبية [%]
    rh_max: 85.0                # الحد الأقصى للرطوبة النسبية [%]
    
    # ✅ قيود الهيدروبونيك المتقدمة
    ph_min: 5.5                 # الحد الأدنى للـ pH
    ph_max: 6.5                 # الحد الأقصى للـ pH
    ec_min: 1.2                 # الحد الأدنى للتوصيلية الكهربائية [mS/cm]
    ec_max: 2.2                 # الحد الأقصى للتوصيلية الكهربائية [mS/cm]
    solution_temp_min: 18.0     # الحد الأدنى لدرجة حرارة المحلول [°C]
    solution_temp_max: 24.0     # الحد الأقصى لدرجة حرارة المحلول [°C]
    ################################################
    ################################################
    #               حط بقيت الهيدروبونيك           #
    ################################################
    ################################################

  eval_options:
    eval_days: [59]             # الأيام المستخدمة في التقييم
    eval_years: [2024]          # السنوات المستخدمة في التقييم
    location: Egypt             # موقع الدفيئة

  reward_params:
    # ✅ التكاليف الأساسية
    fixed_greenhouse_cost: 847.89      # تكلفة ثابتة للصوبه [EGP]
    fixed_co2_cost: 0.85                   # تكلفة CO2 ثابتة [EGP]
    fixed_lamp_cost: 3.96                  # تكلفة الإضاءة [EGP]
    fixed_screen_cost: 113.05              # تكلفة الستائر [EGP]
    
    # ✅ أسعار الطاقة والمواد
    elec_price: 16.96                       # سعر الكهرباء [EGP/kWh]
    heating_price: 5.09                      # سعر التدفئة [EGP/kWh]
    co2_price: 16.96                         # سعر CO2 [EGP/kg]
    fruit_price: 67.83                        # سعر المحصول [EGP/kg]
    
    # ✅ معاملات المحصول
    dmfm: 0.05                         # نسبة المادة الجافة إلى الطازجة
    
    # ✅ أوزان العقوبات
    pen_weights: [4.e-4, 5.e-3, 7.e-4] # أوزان العقوبات للمناخ
    pen_lamp: 0.1                      # عقوبة استهلاك اللمبات
    
    # ✅ عقوبات الهيدروبونيك
    ph_violation_penalty: 0.1          # عقوبة انتهاك pH
    ec_violation_penalty: 0.1          # عقوبة انتهاك EC
    solution_temp_violation_penalty: 0.1 # عقوبة انتهاك درجة حرارة المحلول
    
    

  hydroponic_params:
    # ✅ نوع النظام
    system_type: "NFT"
    
    # ✅ الأهداف المثالية
    target_ph: 6.0                     # درجة الحموضة المثالية
    target_ec: 1.4                     # التوصيلية الكهربائية المثالية [mS/cm]
    
    # ✅ نطاقات التسامح
    ph_tolerance: 0.5                  # نطاق تسامح pH
    ec_tolerance: 0.2                  # نطاق تسامح EC
    
    # ✅ درجة حرارة المحلول
    solution_temp_min: 18.0            # الحد الأدنى لدرجة حرارة المحلول
    solution_temp_max: 24.0            # الحد الأقصى لدرجة حرارة المحلول
    
    # ✅ معدلات التدفق والتهوية
    nutrient_flow_rate: 2.0            # معدل تدفق المغذيات [L/min per plant]
    aeration_rate: 1.0                 # معدل التهوية [L/min per plant]
    
    
    # ✅ إعدادات النظام
    recirculation: True                # تفعيل إعادة تدوير المغذيات
    ph_control: True                   # تفعيل التحكم في pH
    ec_control: True                   # تفعيل التحكم في EC
    
    # ✅ مزيج المغذيات الأساسية [ppm]
    nutrient_mix:
      N: 150                           # النيتروجين
      P: 50                            # الفوسفور
      K: 200                           # البوتاسيوم
      Ca: 150                          # الكالسيوم
      Mg: 50                           # المغنيسيوم
      S: 100                           # الكبريت
    
    # ✅ المغذيات الدقيقة [ppm]
    micronutrients:
      Fe: 2.0                          # الحديد
      Mn: 0.5                          # المنغنيز
      Zn: 0.1                          # الزنك
      Cu: 0.05                         # النحاس
      B: 0.3                           # البورون
      Mo: 0.05                         # الموليبدينوم

# =====================================================================
# ملاحظات مهمة:
# =====================================================================
# 1. تم تحديث عدد المعاملات إلى 208 لدعم الميزات الجديدة
# 2. تم إضافة 8 عناصر تحكم (6 أساسية + 2 للهيدروبونيك)
# 3. تم إضافة قيود جديدة للـ pH و EC ودرجة حرارة المحلول
# 4. تم إضافة عقوبات خاصة بانتهاكات الهيدروبونيك
# 5. تم إضافة معاملات متقدمة لإدارة المغذيات
# =====================================================================

# results_columns: [
#   Time, co2_air, co2_top, temp_air, temp_top, can_temp, covin_temp, covex_temp,
#   thScr_temp, flr_temp, pipe_temp, soil1_temp, soil2_temp, soil3_temp, soil4_temp, soil5_temp, 
#   vp_air, vp_top, lamp_temp, intlamp_temp, grow_pipe_temp, blscr_temp, 24_can_temp,
#   cBuf, cleaves, cstem, cFruit, tsum, glob_rad, temp_out, rh_out, co2_out, wind_speed,
#   heating_setpoint, co2_setpoint, thr_scr, vent_setpoint, lamp,
#   profits, cum_profits, cum_fixed_costs, cum_var_costs, cum_gains, episode
#]

# اعتمدت التعديلات علي بيانات من مصادر موثوقه حول الشروط البيئيه المثاليه للخس في البيوت الزجاجيه,
# مثل نطاق درجات الحراره (18-24 درجه مئويه عاده لذا حد الاقصي 28),
# تركيز CO2(حتي 1300 PPM),
# نسبه الماده الجافه (حوالي 5%)
# وسعر الخس (حوالي 1.2 يورو/كجم بناء علي اسعار الجمله في اوروبا)

# النطاق الأمثل لدرجة الحرارة النهارية يتراوح بين 18-24 درجة مئوية،
# بينما الليلية حوالي 13-18 درجة مئوية. يمكن للخس تحمل درجات حرارة أعلى مؤقتًا،
# لكن النمو يتباطأ فوق 24 درجة مئوية، وقد يحدث الإزهار المبكر (bolting) عند الاقتراب من 30 درجة مئوية أو أكثر،
# وقد يموت النبات عند 37-40 درجة مئوية. لذلك، تم تعديل الحد الأعلى (temp_max) إلى 28 درجة مئوية كقيد آمن لتجنب الأضرار.
