# =====================================================================
# LettuceEnv.yml
# Description: Configuration file for the Lettuce environment (Hydroponic version)
# ุชู ุชุนุฏูู ุงูููู ุจุญูุซ ูุถูู ูููุฏ ุนูู pH ู EC ุจุฌุงูุจ ุงููููุฏ ุงูููุงุฎูุฉ
# =====================================================================

GreenLightEnv:
  weather_data_dir: gl_gym/environments/weather   # ๐ ูุณุงุฑ ุจูุงูุงุช ุงูุทูุณ
  location: Egypt                                 # ๐ ูููุน ุชุณุฌูู ุจูุงูุงุช ุงูุทูุณ
  num_params: 208                                 # ุนุฏุฏ ุจุงุฑุงููุชุฑุงุช ุงููููุฐุฌ
  nx: 28                                          # ุนุฏุฏ ุญุงูุงุช ุงููุธุงู
  nu: 6                                           # ุนุฏุฏ ูุฏุฎูุงุช ุงูุชุญูู
  nd: 10                                          # ุนุฏุฏ ุงูุงุถุทุฑุงุจุงุช ุงูููุงุฎูุฉ
  dt: 900                                         # โฑ๏ธ ุฎุทูุฉ ุฒูููุฉ ูููุญุงูู (ุซูุงูู)
  u_min: [0, 0, 0, 0, 0, 0]                       # ุฃูู ูููุฉ ููุชุญูู
  u_max: [1, 1, 1, 1, 1, 1]                       # ุฃุนูู ูููุฉ ููุชุญูู
  delta_u_max: 0.1                                # ูุนุฏู ุงูุชุบููุฑ ุงูุฃูุตู ูู ุงูุชุญูู
  pred_horizon: 0.5                               # [ุฃูุงู] ุฃูู ุงูุชูุจุค ููุทูุณ
  season_length: 60                               # ุทูู ุงูููุณู (ุจุงูุฃูุงู)
  start_train_year: 2024                          # ุจุฏุงูุฉ ูุชุฑุฉ ุงูุชุฏุฑูุจ (ุณูุฉ)
  end_train_year: 2024                            # ููุงูุฉ ูุชุฑุฉ ุงูุชุฏุฑูุจ (ุณูุฉ)
  start_train_day: 59                             # ุจุฏุงูุฉ ูุชุฑุฉ ุงูุชุฏุฑูุจ (ููู ูู ุงูุณูุฉ)
  end_train_day: 59                               # ููุงูุฉ ูุชุฑุฉ ุงูุชุฏุฑูุจ (ููู ูู ุงูุณูุฉ)
  training: True                                  # ูู ุงููุถุน ุชุฏุฑูุจ ุฃู ุงุฎุชุจุงุฑ

# =====================================================================
# ุฅุนุฏุงุฏุงุช ุงูุจูุฆุฉ ุงูุฎุงุตุฉ ุจุงูู LettuceEnv
# =====================================================================
LettuceEnv:
  reward_function: GreenhouseReward               # ุฏุงูุฉ ุงูููุงูุฃุฉ ุงููุณุชุฎุฏูุฉ

  observation_modules: [                          # ุงููุญุฏุงุช ุงููู ุจุชูุณุชุฎุฏู ูููุงุญุธุงุช
    IndoorClimateObservations,   
    BasicCropObservations, 
    ControlObservations, 
    WeatherObservations,
    TimeObservations,
    WeatherForecastObservations
  ]

  constraints:
    # โ ูููุฏ ุงูููุงุฎ ุงูุฏุงุฎูู
    co2_min: 300.             # ุงูุญุฏ ุงูุฃุฏูู ูุซุงูู ุฃูุณูุฏ ุงููุฑุจูู [ppm]
    co2_max: 1300.            # ุงูุญุฏ ุงูุฃูุตู ูุซุงูู ุฃูุณูุฏ ุงููุฑุจูู [ppm]
    temp_min: 15.             # ุงูุญุฏ ุงูุฃุฏูู ูุฏุฑุฌุฉ ุงูุญุฑุงุฑุฉ [ยฐC]
    temp_max: 28.             # ุงูุญุฏ ุงูุฃูุตู ูุฏุฑุฌุฉ ุงูุญุฑุงุฑุฉ [ยฐC]
    rh_min: 50.               # ุงูุญุฏ ุงูุฃุฏูู ููุฑุทูุจุฉ ุงููุณุจูุฉ [%]
    rh_max: 85.               # ุงูุญุฏ ุงูุฃูุตู ููุฑุทูุจุฉ ุงููุณุจูุฉ [%]

    # โ ูููุฏ ุฅุถุงููุฉ ููููุฏุฑูุจูููู
    ph_min: 5.5               # ุงูุญุฏ ุงูุฃุฏูู ููู pH (ุญููุถุฉ ุงููุญููู ุงููุบุฐู)
    ph_max: 6.5               # ุงูุญุฏ ุงูุฃูุตู ููู pH
    ec_min: 1.2               # ุงูุญุฏ ุงูุฃุฏูู ููุชูุตูููุฉ ุงูููุฑุจูุฉ (mS/cm)
    ec_max: 2.2               # ุงูุญุฏ ุงูุฃูุตู ููุชูุตูููุฉ ุงูููุฑุจูุฉ (mS/cm)

  eval_options:
    eval_days: [59]           # ุงูุฃูุงู ุงููุณุชุฎุฏูุฉ ูู ุงูุชูููู
    eval_years: [2024]        # ุงูุณููุงุช ุงููุณุชุฎุฏูุฉ ูู ุงูุชูููู
    location: Egypt           # ูููุน ุงูุฏููุฆุฉ

  reward_params:
    fixed_greenhouse_cost: 15.        # ุชูููุฉ ุซุงุจุชุฉ ููุฏููุฆุฉ
    fixed_co2_cost: 0.015             # ุชูููุฉ CO2 ุซุงุจุชุฉ
    fixed_lamp_cost: 0.07             # ุชูููุฉ ุงูุฅุถุงุกุฉ (ูุถุฑูุจุฉ ูู ุดุฏุฉ ุงูุฅุถุงุกุฉ)
    fixed_screen_cost: 2.             # ุชูููุฉ ูุชุญ/ุบูู ุงูุณุชุงุฆุฑ
    elec_price: 0.3                   # ุณุนุฑ ุงูููุฑุจุงุก [โฌ/kWh]
    heating_price: 0.09               # ุณุนุฑ ุงูุชุฏูุฆุฉ [โฌ/kWh]
    co2_price: 0.3                    # ุณุนุฑ CO2 [โฌ/kg]
    fruit_price: 1.2                  # ุณุนุฑ ุงููุญุตูู [โฌ/kg]
    dmfm: 0.05                        # ูุณุจุฉ ุงููุงุฏุฉ ุงูุฌุงูุฉ ุฅูู ุงูุทุงุฒุฌุฉ
    pen_weights: [4.e-4, 5.e-3, 7.e-4] # ุฃูุฒุงู ุงูุนููุจุงุช
    pen_lamp: 0.1                     # ุนููุจุฉ ุงุณุชููุงู ุงูููุจุงุช

# results_columns: [
#   Time, co2_air, co2_top, temp_air, temp_top, can_temp, covin_temp, covex_temp,
#   thScr_temp, flr_temp, pipe_temp, soil1_temp, soil2_temp, soil3_temp, soil4_temp, soil5_temp, 
#   vp_air, vp_top, lamp_temp, intlamp_temp, grow_pipe_temp, blscr_temp, 24_can_temp,
#   cBuf, cleaves, cstem, cFruit, tsum, glob_rad, temp_out, rh_out, co2_out, wind_speed,
#   heating_setpoint, co2_setpoint, thr_scr, vent_setpoint, lamp,
#   profits, cum_profits, cum_fixed_costs, cum_var_costs, cum_gains, episode
#]





# ุงุนุชูุฏุช ุงูุชุนุฏููุงุช ุนูู ุจูุงูุงุช ูู ูุตุงุฏุฑ ููุซููู ุญูู ุงูุดุฑูุท ุงูุจูุฆูู ุงููุซุงููู ููุฎุณ ูู ุงูุจููุช ุงูุฒุฌุงุฌูู,
# ูุซู ูุทุงู ุฏุฑุฌุงุช ุงูุญุฑุงุฑู (18-24 ุฏุฑุฌู ูุฆููู ุนุงุฏู ูุฐุง ุญุฏ ุงูุงูุตู 28),
# ุชุฑููุฒ CO2(ุญุชู 1300 PPM),
# ูุณุจู ุงููุงุฏู ุงูุฌุงูู (ุญูุงูู 5%)
# ูุณุนุฑ ุงูุฎุณ (ุญูุงูู 1.2 ููุฑู/ูุฌู ุจูุงุก ุนูู ุงุณุนุงุฑ ุงูุฌููู ูู ุงูุฑูุจุง)


#  ุงููุทุงู ุงูุฃูุซู ูุฏุฑุฌุฉ ุงูุญุฑุงุฑุฉ ุงูููุงุฑูุฉ ูุชุฑุงูุญ ุจูู 18-24 ุฏุฑุฌุฉ ูุฆููุฉุ
#  ุจูููุง ุงูููููุฉ ุญูุงูู 13-18 ุฏุฑุฌุฉ ูุฆููุฉ. ูููู ููุฎุณ ุชุญูู ุฏุฑุฌุงุช ุญุฑุงุฑุฉ ุฃุนูู ูุคูุชูุงุ
#  ููู ุงูููู ูุชุจุงุทุฃ ููู 24 ุฏุฑุฌุฉ ูุฆููุฉุ ููุฏ ูุญุฏุซ ุงูุฅุฒูุงุฑ ุงููุจูุฑ (bolting) ุนูุฏ ุงูุงูุชุฑุงุจ ูู 30 ุฏุฑุฌุฉ ูุฆููุฉ ุฃู ุฃูุซุฑุ
#  ููุฏ ูููุช ุงููุจุงุช ุนูุฏ 37-40 ุฏุฑุฌุฉ ูุฆููุฉ. ูุฐููุ ุชู ุชุนุฏูู ุงูุญุฏ ุงูุฃุนูู (temp_max) ุฅูู 28 ุฏุฑุฌุฉ ูุฆููุฉ ูููุฏ ุขูู ูุชุฌูุจ ุงูุฃุถุฑุงุฑุ
